name: Build application

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: Set up gon
      run: |
        brew tap mitchellh/gon
        brew install mitchellh/gon/gon
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Rebuild lxml from source
      run: |
        pip install --no-binary :all: lxml
      env:
        STATIC_DEPS: "true"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run py2app
      run: python3 setup.py py2app
    - name: Thin package
      run: |
        rm -rf dist/Pilcrow.app/Contents/Resources/lib/python3.8/PyQt5/Qt/lib/Qt{WebEngine,Designer,Quick}*
        rm -rf dist/Pilcrow.app/Contents/Resources/lib/python3.8/PyQt5/Qt/qml/
    - name: Codesign package
      run: |
        codesign -s "Developer ID Application: Simon Cozens (GHYRZM4TBD)" -v --deep --timestamp --entitlements entitlements.plist -o runtime `find dist/Pilcrow.app -name '*.so' -or -name '*.dylib' -or -name '*.framework'` || true
        codesign -s "Developer ID Application: Simon Cozens (GHYRZM4TBD)" -v --deep --timestamp --entitlements entitlements.plist -o runtime `find dist/Pilcrow.app -type f | grep 'framework/Versions/5/'` || true
        codesign -s "Developer ID Application: Simon Cozens (GHYRZM4TBD)" -v --deep --timestamp --entitlements entitlements.plist -o runtime dist/Pilcrow.app
    - name: Package app
      run: |
        ditto -c -k --keepParent "dist/Pilcrow.app" dist/Pilcrow.zip
    - name: Notarize app
      run: |
        gon gon.json
      env:
        AC_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}
        AC_PROVIDER: ${{ secrets.NOTARIZE_PROVIDER }}
    - name: Staple app
      run: |
        xcrun stapler staple dist/Pilcrow.app
        xcrun stapler validate dist/Pilcrow.app
    - name: Repackage stapled app
      run: |
        rm -rf dist/Pilcrow.zip
        ditto -c -k --keepParent "dist/Pilcrow.app" dist/Pilcrow.zip
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: dist/Pilcrow.zip
    - name: Trash Python packages
      run: rm -rf /Users/runner/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/
    - name: Test it can run
      run: |
        mkdir test
        cd test
        unzip ../dist/Pilcrow.zip
        ./Pilcrow.app/Contents/MacOS/Pilcrow &
        sleep 15
        ps auxw | grep Pilcrow.app | grep -v grep
